### PR TITLE
Bug 1952211: Merge tag 'v1.21.0' into openshift-master

### PR DESCRIPTION
**Pull request by Fedosin**
The fix for the bug is https://github.com/kubernetes/cloud-provider-openstack/pull/773

### CODE REVIEW

**Comment by jsafrane** [comment]
Can you please merge a tag instead of master? I know the OpenStack provider is messy and has different tags for different components, just pick the most appropriate one (and hope for the best...)

**Comment by jsafrane** [comment]
And can you please add e2e test to this repo? Merging almost 1500 changed files is dangerous

**Comment by pierreprinetti** [comment]
LGTM: the e2e-openstack-ipi test seems to be successful, if we exclude the tests that can't succeed.

@mdbooth I defer the actual LGTM to you, as you are currently leading our team efforts in defining an upstream/downstream policy.

**Comment by mdbooth** [comment]
/hold for a successful test run

I don't think we can sanction merging a PR this large without tests. If we can't do that we should put everything on hold until we can do that.

**Comment by pierreprinetti** [comment]
/hold cancel
/lgtm
We have a successful run.

**Pull request merged**
