### PR TITLE
Bug OCPBUGS-3700: Protect from `AllocateLoadBalancerNodePorts=false` (#1988)

### PR DESCRIPTION
**Pull request by dulek**
When aforementioned option is set to `false` on the Service `.spec`, the NodePorts stop being allocated and set for that Service, effectively defaulting all `.spec.ports[*].nodePort` to 0. Similar situation happens with `healthCheckNodePort`. When cloud provider tries to create a member or SG with such a port, Octavia fails.

This commit makes sure we are not adding members when `nodePort` value is 0. We also omit the SG manipulations for such ports.

### CODE REVIEW

**Comment by dulek** [comment]
/assign @mandre 

Please take a look, as you've accepted the release-4.13 merge of this one.

**Review by mandre — COMMENTED** [review]
/lgtm
/approve
/hold for CI

**Comment by mandre** [comment]
The CI failure has nothing to do with the patch.
/hold cancel
/test required

**Comment by dulek** [comment]
/retest-required

Issues with LBs on Vexxhost should be fixed by now.

**Comment by dulek** [comment]
> Is it a legitimate issue? /retest-required

It does cause a test in e2e suite to fail, so kind of. It's probably not a 100% suitable use case for OpenShift on OpenStack though.

**Comment by mandre** [comment]
> > Is it a legitimate issue? /retest-required
> 
> It does cause a test in e2e suite to fail, so kind of. It's probably not a 100% suitable use case for OpenShift on OpenStack though.

Sorry, I was referring to the CI failure and was wondering if it was a legitimate failure. Looks like it passed on the last run so I guess not.

**Pull request merged**
