### PR TITLE
[manila-csi-plugin] Bug 1944655: Ignore proxy connecting to CSI sockets

### PR DESCRIPTION
**Pull request by mdbooth**
```release-note
NONE
```

This is a backport of https://github.com/kubernetes/cloud-provider-openstack/pull/1528, which hasn't landed upstream yet but looks like it will.

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
until the upstream PR lands, we've been bitten by upstream changing its mind several times.
In addition, please update vendor dir, `go mod vendor`.

**Comment by mandre** [comment]
The upstream change merged, we can now land this one. Keeping the hold until CI passes.
/retest
/lgtm

**Comment by jsafrane** [comment]
You need to update `vendor/` with the new grpc

**Review by Fedosin — APPROVED** [review]
/lgtm
/hold

**Comment by mandre** [comment]
There's an infra issue causing e2e-openstack to fail at the moment, where VM end up in ERROR state. We've reported the issue to our cloud provider.

**Comment by Fedosin** [comment]
okay, e2e-openstack-ipi passed. basically it is the same as e2e-openstack, so I'm okay to remove the hold

/hold cancel

**Pull request merged**
