### PR TITLE
Bug 1969345: Backport ignore proxy connecting to CSI sockets 

### PR DESCRIPTION
**Pull request by mdbooth**
**What this PR does / why we need it**:

**Which issue this PR fixes(if applicable)**:
fixes #

**Special notes for reviewers**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.00

approved

**Comment by jsafrane** [comment]
Approving the cherry pick on behalf of @mfojtik

**Pull request merged**
