### PR TITLE
Bug 1820238: Fetch latest changes from upstream

### PR DESCRIPTION
**Pull request by Fedosin**
This patch fetches all latest changes from upstream.
https://github.com/openshift/cloud-provider-openstack/commit/90378cf639cd8bab721bead7e1d5f896b8b768c0 is important to fix the issue with remaining manila shares after cluster deletion.

### CODE REVIEW

**Comment by EmilienM** [comment]
don't we want to run e2e-openstack job?

**Comment by Fedosin** [comment]
oh... looks like we don't have any :(

**Comment by mandre** [comment]
This repo is used for cinder csi and manila csi, and in the future for the external cloud provider.
The basic e2e-openstack parallel test suite woudn't test any of the changes introduced in this patch, we would need to run the CSI tests for this. Although I'm not super happy with the situation, we don't have other choices than blindly accept these changes and hope they don't break cinder CSI or manila CSI.

**Pull request merged**
