### PR TITLE
Sync from upstream

### PR DESCRIPTION
**Pull request by dulek**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
what the
/retest-required

**Comment by pierreprinetti** [comment]
I wonder if there is a change to be made [to the openstack-test](https://github.com/openshift/openstack-test/blob/7217c2880480e5a229379c053797f3856b5e0802/test/extended/openstack/loadbalancers.go#L101) as well?

**Comment by MaysaMacedo** [comment]
@dulek IMHO we can override that job given the failing test in unrelated to this PR

**Comment by MaysaMacedo** [comment]
/override ci/prow/e2e-openstack

Test failure is unrelated to this work, so I'm overriding CI.
Here you can see it has been failing for a while https://search.ci.openshift.org/?search=The+Openstack+platform+should+create+a+TCP+Amphora+LoadBalancer+when+LoadBalancerService+ingressController+is+created+on+Openshift&maxAge=336h&context=1&type=junit&name=e2e-openstack&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by dulek** [comment]
Right, looks like the result's the same here. I'm fine with overriding it, let's see.

/override ci/prow/e2e-openstack

**Pull request merged**
