### PR TITLE
OCPBUGS-5012: Sync with upstream release-1.23

### PR DESCRIPTION
**Pull request by mandre**
Merge  kubernetes/cloud-provider-openstack/release-1.23 into openshift/cloud-provider-openstacl/release-4.10

### CODE REVIEW

**Comment by pierreprinetti** [comment]
à propos: https://github.com/openshift/release/pull/35044

**Comment by dulek** [comment]
/lgtm

So in 4.10 we only use Cinder CSI from this, right? CCM is not yet available.

**Comment by mandre** [comment]
> /lgtm
> 
> So in 4.10 we only use Cinder CSI from this, right? CCM is not yet available.

Correct, however CCM is TP in 4.10, but the job is green as well.

**Comment by dulek** [comment]
I'm not 100% sure we should add a JIRA bug related to just one commit from all this merge.

**Comment by mandre** [comment]
> I'm not 100% sure we should add a JIRA bug related to just one commit from all this merge.

Do you suggest to have a generic "Sync with upstream" jira issue instead? I'm not opposed to it if you want to take care of creating the bug and having it in a valid state for merging (including parent bug).

**Comment by dulek** [comment]
> > I'm not 100% sure we should add a JIRA bug related to just one commit from all this merge.
> 
> Do you suggest to have a generic "Sync with upstream" jira issue instead? I'm not opposed to it if you want to take care of creating the bug and having it in a valid state for merging (including parent bug).

That would not be a real bug too. :/ My point is that this PR includes much more than that bugfix and later on it can be confusing if e.g. we want to backport it further (I know, we won't need it in 4.9 as CCM is not there). This is just a general remark to the process and I don't really have a better solution besides splitting such syncs into multiple PRs. We take care of that in Kuryr, but obviously it takes even more time.

**Pull request merged**
