### PR TITLE
OCPBUGS-16783: Chore: Update OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by mpatlasov**
Adding Jonathan and Roman and Maxim in storage maintainers.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
Looks good to me but would like @jsafrane to weight in.

**Comment by dobsonj** [comment]
> Looks good to me but would like @jsafrane to weight in.

/lgtm
/assign @jsafrane 
  for approval if he agrees

**Pull request merged**
