### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by mdbooth**
This is a mechanical merge of upstream:master into openshift:master with 2 changes:

* Resolved a merge conflict in go.mod with grpc versions
* Reverted commit 68be840e77402587f13197ca39009120d8511a23 from the v1.21.0 release tag which pins images to v1.21.0

### CODE REVIEW

**Comment by pierreprinetti** [comment]
The CI settings are off, it makes no sense to start two e2e jobs --> https://github.com/openshift/release/pull/19364

**Comment by jsafrane** [comment]
It's definitely up to you how you maintain you openshift fork of the cloud provider, still, would it be better to merge some upstream tag instead of unreleased master?

**Comment by mdbooth** [comment]
> 
> 
> It's definitely up to you how you maintain you openshift fork of the cloud provider, still, would it be better to merge some upstream tag instead of unreleased master?

@jsafrane No: http://mailman-int.corp.redhat.com/archives/aos-devel/2021-June/msg00157.html . Until I'm convinced otherwise I think we should never merge release tags into master. I do think we should only merge release tags into release branches, though.

Incidentally, this is prep for automating these merges, and I plan to do the same for csi-driver-nfs.

**Comment by pierreprinetti** [comment]
(openstack tests both failing because of infra issues)

**Comment by pierreprinetti** [comment]
/hold cancel
:tada:

**Pull request merged**
