### PR TITLE
NO-JIRA: CARRY: Restore OWNERS to upstream

### PR DESCRIPTION
**Pull request by dulek**
We are now using DOWNSTREAM_OWNERS instead. We can restore OWNERS and OWNERS_ALIASES to upstream to avoid future merge conflicts.

/hold

### CODE REVIEW

**Comment by dulek** [comment]
This has to wait for #223 and https://github.com/openshift/release/pull/44277.

**Comment by mdbooth** [comment]
/remove-lifecycle stale
/lgtm

@mandre How to I indicate that a Jira makes no sense here?

**Comment by mandre** [comment]
/rename No-JIRA: CARRY: Restore OWNERS to upstream

**Comment by mandre** [comment]
/retitle NO-JIRA: CARRY: Restore OWNERS to upstream

**Comment by mdbooth** [comment]
> this requires [openshift/release#44277](https://github.com/openshift/release/pull/44277)

We can still remove the hold because verify-owners won't pass until it merges.

**Comment by mandre** [comment]
I'm about to rebase master on top of upstream release-1.29 and I've included this change already.
/hold

**Pull request closed without merging**
