### PR TITLE
OCPBUGS-34137, OCPBUGS-34460, OCPBUGS-34113, OCPBUGS-35462: sync upstream on release-1.30/go1.22

### PR DESCRIPTION
**Pull request by EmilienM**
Commands used:

```
git clone https://github.com/openshift/cloud-provider-openstack.git                                                                                                                                                                                                               
cd cloud-provider-openstack                                                                                                                                                                                                                                                       
git remote add openshift https://github.com/openshift/cloud-provider-openstack.git                                                                                                                                                                                                
git remote add kubernetes https://github.com/kubernetes/cloud-provider-openstack.git                                                                                                                                                                                              
git fetch kubernetes release-1.30                                                                                                                                                                                                                                                 
git fetch openshift master                                                                                                                                                                                                                                                        
git checkout -b sync-master openshift/master                                                                                                                                                                                                                                      
git rebase -i kubernetes/release-1.30                                                                                                                                                                                                                                             
# Drop any CARRY: Vendoring commit                                                                                                                                                                                                                                                
# Drop any conflicting CARRY commit related to upstream CI not required downstream
```

Then apply patches from:
* https://github.com/openshift/cloud-provider-openstack/pull/283
* https://github.com/openshift/cloud-provider-openstack/pull/282
* https://github.com/openshift/cloud-provider-openstack/pull/281

- **Use k3s with containerd (#2529)**
- **CI: Fetch DevStack and k3s logs (#2527)**
- **Ingress: Fix listener timeout updates (#2518)**
- **Add support to only run selected CSI services (#2316)**
- **[ci] Bump golangci-lint for go 1.22 (#2544)**
- **cinder-csi: Adds support for managing backups (#2473) (#2480)**
- **fix: add missing labels to resources (#2519)**
- **[octavia-ingress-controller] Add annotations to keep floating IP and/or specify an existing floating IP (#2166)**
- **Pass KeyId to EncryptResponse (#2535)**
- **Improve CCM docs in dual-stack context (#2563)**
- **Update KMS API to v2 (#2561)**
- **Remove enforcement of IPv6 LB as internal (#2557)**
- **Convert outstanding commands to cobra (#2384)**
- **Update the release procedure (#2565)**
- **Allow changing cluster-name on existing deployments (#2552)**
- **added route section to cloud-config secret (#2570)**
- **[cinder-csi-plugin] define availability zone for snapshot backup (#2569)**
- **Set `--use-service-account-credentials=false` (#2572)**
- **Update Cinder and Manila CSI charts maintainers (#2583)**
- **Bump K8s to v1.30.0 (#2581)**
- **[occm] KEP-1860: Add support for LoadBalancer ipMode (#2587)**
- **Bump versions for 1.30 (#2589)**
- **[release-1.30] [occm] add a node selector support for loadbalancer services (#2603)**
- **CARRY: Add DOWNSTREAM_OWNERS**
- **CARRY: Add .snyk configuration file**
- **CARRY: Add images**
- **CARRY: More snyk ignores**
- **Updating ose-openstack-cinder-csi-driver-container image to be consistent with ART for 4.17 Reconciling with https://github.com/openshift/ocp-build-data/tree/0a1310d4df1f00e3e218da6e356585997c7c0178/images/ose-openstack-cinder-csi-driver.yml**
- **Remove dulek from shiftstack-team**
- **UPSTREAM: <carry>: Updating ose-openstack-cloud-controller-manager-container image to be consistent with ART for 4.17**
- **UPSTREAM: <carry>: Updating ose-openstack-cinder-csi-driver-container image to be consistent with ART for 4.17**
- **UPSTREAM: <carry>: Updating csi-driver-manila-container image to be consistent with ART for 4.17**

### CODE REVIEW

**Comment by EmilienM** [comment]
/override ci/prow/e2e-openstack
The only failure is fixed via https://github.com/openshift/openstack-test/pull/175

**Comment by EmilienM** [comment]
/test e2e-openstack-csi-manila 
timeout :/

**Review by mandre — COMMENTED** [review]
LGTM on principle, still I'd like so see the results from the Manila CSI job.

**Comment by EmilienM** [comment]
/override ci/prow/e2e-openstack-csi-cinder 
The results indicates a failure on a LOW impact test that fails all the time (we should fix or skip it).

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cloud-provider-openstack/287/pull-ci-openshift-cloud-provider-openstack-master-e2e-openstack-csi-cinder/1802697896110329856

**Comment by EmilienM** [comment]
/override ci/prow/e2e-openstack-csi-manila
The error is low

**Review by mandre — COMMENTED** [review]
The failure in the CSI jobs is a known issue ([OCPBUGS-31738](https://issues.redhat.com/browse/OCPBUGS-31738)) and is unrelated to this change.
/lgtm
/approve

**Pull request merged**
