### PR TITLE
OCPBUGS-20124: FastFix: Merge https://github.com/kubernetes/cloud-provider-openstack:release-1.25 into release-4.12

### PR DESCRIPTION
**Pull request by mandre**
Replaces #209 
```
Conflicts:
      OWNERS
```

### CODE REVIEW

**Comment by dulek** [comment]
/retitle OCPBUGS-20124: Merge https://github.com/kubernetes/cloud-provider-openstack:release-1.25 into release-4.12

**Review by mandre — COMMENTED** [review]
/label backport-risk-assessed

**Comment by rlobillo** [comment]
Pre-verified in custom OCP4.12 payload including this fix (thanks to cluster-bot) on top of RHOS-16.2-RHEL-8-20230510.n.1.

 1. Edit cinder.conf on the controllers:

```
sudo -i
mv /var/lib/config-data/puppet-generated/cinder/etc/cinder/cinder.conf /var/lib/config-data/puppet-generated/cinder/etc/cinder/cinder.conf_bk
sed 's/#osapi_max_limit =.*/osapi_max_limit = 9/' /var/lib/config-data/puppet-generated/cinder/etc/cinder/cinder.conf_bk > /var/lib/config-data/puppet-generated/cinder/etc/cinder/cinder.conf
podman ps -a |grep cinder_api$ | awk '{print $1}' | xargs podman restart
podman exec -it cinder_api grep osapi_max_limit /etc/cinder/cinder.conf 
osapi_max_limit = 9

```
2. monitor csi-attacher logs:

`$ oc logs  -n openshift-cluster-csi-drivers -c csi-attacher -l app=openstack-cinder-csi-driver-controller -f`

3. Apply [extra_pvc.yaml](https://privatebin.corp.redhat.com/?4681fa9504332eb8#3dtJWkNKD9uHuUvpUEL998Unjet9QNX7YtVaY6BAqyvi) and wait for logs:

```
I1011 09:44:41.017089       1 csi_handler.go:251] Attaching "csi-604cfacec3b7a9f4ee19db7fb75503865918988ba4834c30ad28647582e484b4"
I1011 09:44:46.160694       1 csi_handler.go:264] Attached "csi-604cfacec3b7a9f4ee19db7fb75503865918988ba4834c30ad28647582e484b4"
I1011 09:44:49.987966       1 csi_handler.go:251] Attaching "csi-7aa553e1eb1dd8140b36b92d3bf022cccbd47bcea8c002233019fc5667de1e96"
I1011 09:44:54.258573       1 csi_handler.go:264] Attached "csi-7aa553e1eb1dd8140b36b92d3bf022cccbd47bcea8c002233019fc5667de1e96"
I1011 09:44:55.932280       1 csi_handler.go:251] Attaching "csi-21dbc49f6c15007c8299e06dceb65c62b4706e2dab254852bf37a50bb629d610"
I1011 09:44:59.449034       1 csi_handler.go:264] Attached "csi-21dbc49f6c15007c8299e06dceb65c62b4706e2dab254852bf37a50bb629d610"                                                                                                            
I1011 09:49:10.389687       1 csi_handler.go:251] Attaching "csi-56b5c4799be147d059cbce2bba61853a67e09711fafae6b889677f2c342015c9"                                                                                                           
I1011 09:49:10.391690       1 csi_handler.go:251] Attaching "csi-5680a8cfe38af997349eb1648609d82d726805efa9e75a75aabcc36dfdc07892"                                                                                                           
I1011 09:49:10.392602       1 csi_handler.go:251] Attaching "csi-6d95858639ceeed0d540188432e0f0ee086142acbaf602f83b24af9f0176d4dc"                                                                                                           
I1011 09:49:10.394018       1 csi_handler.go:251] Attaching "csi-118e97d558f1452650752fac568b16c3968c1f7114a948657b1c452201c49d74"                                                                                                           
I1011 09:49:10.394812       1 csi_handler.go:251] Attaching "csi-ca1a6d31b21928bc39f8b36a05cccab874b78ca4c2f6b9b4400f660e5d34e6e2"                                                                                                           
I1011 09:49:10.396311       1 csi_handler.go:251] Attaching "csi-25ee14c15e09e19023f6b19a674968a65a22ecfa856f69736bf876a7e3160219"                                                                                                           
I1011 09:49:10.396323       1 csi_handler.go:251] Attaching "csi-3b3886c6beac817ce18721e33d234817666fb2cb607656c1d19c52002a6b6973"                                                                                                           
I1011 09:49:10.396447       1 csi_handler.go:251] Attaching "csi-85d6b276f7d643b0268317a3acd88508d2250eaa3949674ca6b7cd653fb91b47"                                                                                                           
I1011 09:49:10.396734       1 csi_handler.go:251] Attaching "csi-6e596cc7fcc75c900470a22dc1fa65628e457ab68ad3d10df0e47215bbb033bf"                                                                                                           
I1011 09:49:10.404467       1 csi_handler.go:251] Attaching "csi-a2be6c1c7a82cc9d6d894f9494c31ef63eb897137d42eceeb0fce6f5643daecd"                                                                                                           
I1011 09:49:11.593053       1 request.go:601] Waited for 1.175257545s due to client-side throttling, not priority and fairness, request: PATCH:https://172.30.0.1:443/apis/storage.k8s.io/v1/volumeattachments/csi-a2be6c1c7a82cc9d6d894f9494c
31ef63eb897137d42eceeb0fce6f5643daecd
I1011 09:49:14.350760       1 csi_handler.go:264] Attached "csi-56b5c4799be147d059cbce2bba61853a67e09711fafae6b889677f2c342015c9"                                                                                                            
I1011 09:49:14.371742       1 csi_handler.go:251] Attaching "csi-88c13ec021bbd3b9cba720b3de843497731be4fdfab5451710a40cff1e900dce"                                                                                                           
I1011 09:49:16.038885       1 csi_handler.go:264] Attached "csi-118e97d558f1452650752fac568b16c3968c1f7114a948657b1c452201c49d74"                                                                                                            
I1011 09:49:17.685980       1 csi_handler.go:264] Attached "csi-6d95858639ceeed0d540188432e0f0ee086142acbaf602f83b24af9f0176d4dc"                                                                                                            
I1011 09:49:19.696518       1 csi_handler.go:264] Attached "csi-5680a8cfe38af997349eb1648609d82d726805efa9e75a75aabcc36dfdc07892"                                                                                                            
I1011 09:49:19.804973       1 csi_handler.go:264] Attached "csi-a2be6c1c7a82cc9d6d894f9494c31ef63eb897137d42eceeb0fce6f5643daecd"                                                                                                            
I1011 09:49:22.073909       1 csi_handler.go:264] Attached "csi-25ee14c15e09e19023f6b19a674968a65a22ecfa856f69736bf876a7e3160219"                                                                                                            
I1011 09:49:22.185865       1 csi_handler.go:264] Attached "csi-3b3886c6beac817ce18721e33d234817666fb2cb607656c1d19c52002a6b6973"                                                                                                            
I1011 09:49:22.193684       1 csi_handler.go:251] Attaching "csi-3b3886c6beac817ce18721e33d234817666fb2cb607656c1d19c52002a6b6973"                                                                                                           
I1011 09:49:22.756997       1 csi_handler.go:264] Attached "csi-3b3886c6beac817ce18721e33d234817666fb2cb607656c1d19c52002a6b6973"                                                                                                            
I1011 09:49:24.844247       1 csi_handler.go:264] Attached "csi-6e596cc7fcc75c900470a22dc1fa65628e457ab68ad3d10df0e47215bbb033bf"                                                                                                            
I1011 09:49:24.853774       1 csi_handler.go:251] Attaching "csi-6e596cc7fcc75c900470a22dc1fa65628e457ab68ad3d10df0e47215bbb033bf"                                                                                                           
I1011 09:49:24.954603       1 csi_handler.go:264] Attached "csi-85d6b276f7d643b0268317a3acd88508d2250eaa3949674ca6b7cd653fb91b47"                                                                                                            
I1011 09:49:25.500421       1 csi_handler.go:264] Attached "csi-6e596cc7fcc75c900470a22dc1fa65628e457ab68ad3d10df0e47215bbb033bf"                                                                                                            
I1011 09:49:27.287910       1 csi_handler.go:264] Attached "csi-ca1a6d31b21928bc39f8b36a05cccab874b78ca4c2f6b9b4400f660e5d34e6e2"                                                                                                            
I1011 09:49:28.849377       1 csi_handler.go:264] Attached "csi-88c13ec021bbd3b9cba720b3de843497731be4fdfab5451710a40cff1e900dce"      

```
The line:

.*Adding back to VA queue for forced reprocessing.*
is not observed on the csi-attacher container logs.

/label qe-approved

**Comment by dulek** [comment]
/retitle OCPBUGS-20124: FastFix: Merge https://github.com/kubernetes/cloud-provider-openstack:release-1.25 into release-4.12

**Pull request merged**
